"""
Proposal and related models.

A Proposal represents an AI-generated architecture recommendation for a project.
It can have multiple variations (from different AI personas) and associated debate
sessions where agents discuss trade-offs.

Models:
    - Proposal: Main architecture proposal
    - ProposalVariation: AI-generated alternative approaches
    - TaskDocument: Documents specific to this proposal task

Relationships:
    Proposal:
        - project: Parent project
        - variations: Different AI-generated approaches
        - debate_sessions: Multi-agent debates about this proposal
        - task_documents: Uploaded context documents
"""

from datetime import datetime, timezone
from enum import Enum
from typing import Optional, List, Dict, TYPE_CHECKING

from sqlmodel import (
    SQLModel,
    Field,
    Relationship,
    Column,
    Integer,
    ForeignKey,
    String,
    Text,
)
from sqlalchemy import Enum as SAEnum, Index
from sqlalchemy.dialects.postgresql import JSONB

if TYPE_CHECKING:
    from app.models.debate import DebateSession
    from app.models.project import Project
    from app.models.user import User


# ==================== Enums ====================


class ProposalStatus(str, Enum):
    """
    Proposal generation status.

    States:
        DRAFT: Initial state, not yet processed
        PROCESSING: AI agents are generating proposal
        COMPLETED: Successfully generated
        FAILED: Generation failed
    """

    DRAFT = "DRAFT"
    PROCESSING = "PROCESSING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"

    @classmethod
    def default(cls) -> "ProposalStatus":
        """Get default status for new proposals."""
        return cls.DRAFT


class ApprovalStatus(str, Enum):
    """
    Proposal approval workflow status.

    States:
        DRAFT: Not yet submitted for review
        PENDING_APPROVAL: Awaiting review
        IN_REVIEW: Currently being reviewed
        APPROVED: Approved for implementation
        REJECTED: Rejected
        REVISION_NEEDED: Needs changes before approval
    """

    DRAFT = "DRAFT"
    PENDING_APPROVAL = "PENDING_APPROVAL"
    IN_REVIEW = "IN_REVIEW"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    REVISION_NEEDED = "REVISION_NEEDED"

    @classmethod
    def default(cls) -> "ApprovalStatus":
        """Get default approval status."""
        return cls.DRAFT


class AgentPersona(str, Enum):
    """
    AI agent personas for multi-agent debates.

    Personas:
        LEGACY_KEEPER: Prioritizes stability, risk mitigation
        INNOVATOR: Advocates for modern solutions, velocity
        MEDIATOR: Balances trade-offs, pragmatic approach
    """

    LEGACY_KEEPER = "LEGACY_KEEPER"
    INNOVATOR = "INNOVATOR"
    MEDIATOR = "MEDIATOR"
    BASELINE = "BASELINE"  # For single-agent baseline proposals


# ==================== Proposal Model ====================


class Proposal(SQLModel, table=True):
    """
    Architecture proposal generated by AI agents.

    Contains the main proposal description, multiple variations from different
    AI personas, and associated debate sessions.

    Attributes:
        id: Primary key
        task_description: Original user request/task
        structured_prd: Generated PRD (Product Requirements Document)
        status: Generation status (draft/processing/completed/failed)
        approval_status: Workflow approval status
        error_message: Error details if generation failed
        selected_variation_id: User's selected variation (FK to ProposalVariation)
        project_id: Parent project (FK)
        created_by_id: User who created this proposal
        created_at: Creation timestamp
        updated_at: Last update timestamp
    """

    __tablename__ = "proposals"

    # ==================== Primary Key ====================

    id: Optional[int] = Field(
        default=None,
        primary_key=True,
        description="Proposal ID",
    )

    # ==================== Core Content ====================

    task_description: str = Field(
        sa_column=Column(Text, nullable=False),
        description="Original user request/task description",
    )

    structured_prd: Optional[str] = Field(
        default=None,
        sa_column=Column(Text),
        description="Generated Product Requirements Document (Markdown)",
    )

    # ==================== Status ====================

    status: ProposalStatus = Field(
        default=ProposalStatus.DRAFT,
        sa_column=Column(
            SAEnum(
                ProposalStatus,
                name="proposalstatus",
                create_type=False,
                native_enum=True,
                values_callable=lambda e: [m.value for m in e],
            ),
            index=True,
            nullable=False,
        ),
        description="Proposal generation status",
    )

    approval_status: ApprovalStatus = Field(
        default=ApprovalStatus.DRAFT,
        sa_column=Column(
            SAEnum(
                ApprovalStatus,
                name="approvalstatus",
                create_type=False,
                native_enum=True,
                values_callable=lambda e: [m.value for m in e],
            ),
            index=True,
            nullable=False,
        ),
        description="Approval workflow status",
    )

    error_message: Optional[str] = Field(
        default=None,
        sa_column=Column(Text),
        description="Error message if generation failed",
    )

    # ==================== Selection ====================

    selected_variation_id: Optional[int] = Field(
        default=None,
        sa_column=Column(
            Integer,
            ForeignKey("proposal_variations.id", ondelete="SET NULL"),
            nullable=True,
        ),
        description="ID of user-selected variation",
    )

    # ==================== Foreign Keys ====================

    project_id: int = Field(
        foreign_key="projects.id",
        index=True,
        ondelete="CASCADE",
        description="Parent project ID",
    )

    created_by_id: Optional[int] = Field(
        default=None,
        foreign_key="users.id",
        index=True,
        description="User who created this proposal",
    )

    # ==================== Timestamps ====================

    created_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc).replace(tzinfo=None),
        nullable=False,
        index=True,
        description="Creation timestamp (UTC)",
    )

    updated_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc).replace(tzinfo=None),
        nullable=False,
        sa_column_kwargs={
            "onupdate": lambda: datetime.now(timezone.utc).replace(tzinfo=None)
        },
        description="Last update timestamp (UTC)",
    )

    approved_at: Optional[datetime] = Field(
        default=None,
        description="Approval timestamp",
    )

    approved_by_id: Optional[int] = Field(
        default=None,
        foreign_key="users.id",
        description="User who approved this proposal",
    )

    rejection_reason: Optional[str] = Field(
        default=None,
        sa_column=Column(Text),
        description="Reason for rejection",
    )

    revision_feedback: Optional[str] = Field(
        default=None,
        sa_column=Column(Text),
        description="Feedback for requested revision",
    )

    # ==================== Jira Export ====================

    jira_epic_key: Optional[str] = Field(
        default=None,
        max_length=50,
        description="Jira epic key created from this proposal (e.g. PROJ-42)",
    )

    jira_epic_url: Optional[str] = Field(
        default=None,
        max_length=500,
        description="Full URL to the Jira epic",
    )

    jira_project_key: Optional[str] = Field(
        default=None,
        max_length=20,
        description="Jira project key used for export (e.g. PROJ)",
    )

    jira_exported_at: Optional[datetime] = Field(
        default=None,
        description="Timestamp of last Jira export",
    )

    # ==================== Confluence Export ====================

    confluence_page_id: Optional[str] = Field(
        default=None,
        max_length=50,
        description="Confluence page ID created from this proposal",
    )

    confluence_page_url: Optional[str] = Field(
        default=None,
        max_length=500,
        description="Full URL to the Confluence page",
    )

    confluence_space_key: Optional[str] = Field(
        default=None,
        max_length=50,
        description="Confluence space key used for export (e.g. ARCH)",
    )

    confluence_exported_at: Optional[datetime] = Field(
        default=None,
        description="Timestamp of last Confluence export",
    )

    # ==================== Relationships ====================

    project: "Project" = Relationship(
        back_populates="proposals",
        sa_relationship_kwargs={"lazy": "selectin"},
    )

    variations: List["ProposalVariation"] = Relationship(
        back_populates="proposal",
        sa_relationship_kwargs={
            "lazy": "selectin",
            "cascade": "all, delete-orphan",
            "foreign_keys": "[ProposalVariation.proposal_id]",
        },
    )

    debate_sessions: List["DebateSession"] = Relationship(
        back_populates="proposal",
        sa_relationship_kwargs={
            "lazy": "selectin",
            "cascade": "all, delete-orphan",
        },
    )

    task_documents: List["TaskDocument"] = Relationship(
        back_populates="proposal",
        sa_relationship_kwargs={
            "lazy": "selectin",
            "cascade": "all, delete-orphan",
        },
    )

    # ==================== Indexes ====================

    __table_args__ = (
        Index("idx_proposal_project_status", "project_id", "status"),
        Index("idx_proposal_approval", "approval_status", "created_at"),
        Index("idx_proposal_created_by", "created_by_id", "created_at"),
    )

    # ==================== Helper Methods ====================

    @property
    def is_completed(self) -> bool:
        """Check if proposal generation is complete."""
        return self.status == ProposalStatus.COMPLETED

    @property
    def is_approved(self) -> bool:
        """Check if proposal is approved."""
        return self.approval_status == ApprovalStatus.APPROVED

    @property
    def is_pending_review(self) -> bool:
        """Check if proposal is awaiting review."""
        return self.approval_status in (
            ApprovalStatus.PENDING_APPROVAL,
            ApprovalStatus.IN_REVIEW,
        )

    @property
    def has_variations(self) -> bool:
        """Check if proposal has any variations."""
        return len(self.variations) > 0

    @property
    def variation_count(self) -> int:
        """Get number of variations."""
        return len(self.variations)

    def mark_processing(self) -> None:
        """Mark proposal as currently processing."""
        self.status = ProposalStatus.PROCESSING
        self.updated_at = datetime.now(timezone.utc).replace(tzinfo=None)

    def mark_completed(self) -> None:
        """Mark proposal as successfully completed."""
        self.status = ProposalStatus.COMPLETED
        self.error_message = None
        self.updated_at = datetime.now(timezone.utc).replace(tzinfo=None)

    def mark_failed(self, error: str) -> None:
        """Mark proposal as failed with error message."""
        self.status = ProposalStatus.FAILED
        self.error_message = error
        self.updated_at = datetime.now(timezone.utc).replace(tzinfo=None)

    def submit_for_approval(self) -> None:
        """Submit proposal for approval."""
        self.approval_status = ApprovalStatus.PENDING_APPROVAL
        self.updated_at = datetime.now(timezone.utc).replace(tzinfo=None)

    def approve(self, approved_by_id: int) -> None:
        """Approve this proposal."""
        self.approval_status = ApprovalStatus.APPROVED
        self.approved_at = datetime.now(timezone.utc).replace(tzinfo=None)
        self.approved_by_id = approved_by_id
        self.updated_at = datetime.now(timezone.utc).replace(tzinfo=None)

    def reject(self, reason: str = "") -> None:
        """Reject this proposal."""
        self.approval_status = ApprovalStatus.REJECTED
        self.rejection_reason = reason
        self.updated_at = datetime.now(timezone.utc).replace(tzinfo=None)

    def request_revision(self, feedback: str = "") -> None:
        """Request revisions to proposal."""
        self.approval_status = ApprovalStatus.REVISION_NEEDED
        self.revision_feedback = feedback
        self.updated_at = datetime.now(timezone.utc).replace(tzinfo=None)

    def __repr__(self) -> str:
        """String representation for debugging."""
        return f"<Proposal(id={self.id}, status={self.status.value}, project_id={self.project_id})>"


# ==================== ProposalVariation Model ====================


class ProposalVariation(SQLModel, table=True):
    """
    AI-generated variation of a proposal from a specific persona.

    Each proposal can have multiple variations generated by different AI
    agent personas (Legacy Keeper, Innovator, Mediator).

    Attributes:
        id: Primary key
        agent_persona: Which AI persona generated this
        structured_prd: Generated PRD content
        confidence_score: AI's confidence in this approach (0-100)
        reasoning: Explanation of approach
        trade_offs: Identified trade-offs
        chat_history: Conversation history with this agent
        proposal_id: Parent proposal (FK)
        created_at: Generation timestamp
    """

    __tablename__ = "proposal_variations"

    # ==================== Primary Key ====================

    id: Optional[int] = Field(
        default=None,
        primary_key=True,
        description="Variation ID",
    )

    # ==================== Agent Info ====================

    agent_persona: AgentPersona = Field(
        sa_column=Column(
            SAEnum(
                AgentPersona,
                name="agentpersona",
                create_type=False,
                native_enum=True,
                values_callable=lambda e: [m.value for m in e],
            )
        ),
        description="AI persona that generated this variation",
    )

    # ==================== Content ====================

    structured_prd: str = Field(
        sa_column=Column(Text, nullable=False),
        description="Generated PRD content (Markdown)",
    )

    reasoning: Optional[str] = Field(
        default=None,
        sa_column=Column(Text),
        description="Explanation of why this approach was chosen",
    )

    trade_offs: Optional[str] = Field(
        default=None,
        sa_column=Column(Text),
        description="Identified trade-offs of this approach",
    )

    # ==================== Metrics ====================

    confidence_score: int = Field(
        default=50,
        ge=0,
        le=100,
        description="AI confidence in this approach (0-100)",
    )

    generation_seconds: Optional[float] = Field(
        default=None,
        ge=0.0,
        description=(
            "Wall-clock generation time in seconds. "
            "Populated for baseline (Condition A) variations so RQ3 "
            "efficiency can be compared against multi-agent duration_seconds."
        ),
    )

    # ==================== Interaction History ====================

    chat_history: List[Dict[str, str]] = Field(
        default=[],
        sa_column=Column(JSONB),
        description="Conversation history with this AI persona",
    )

    # ==================== Foreign Keys ====================

    proposal_id: int = Field(
        foreign_key="proposals.id",
        index=True,
        description="Parent proposal ID",
    )

    # ==================== Timestamps ====================

    created_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc).replace(tzinfo=None),
        nullable=False,
        description="Generation timestamp (UTC)",
    )

    # ==================== Relationships ====================

    proposal: Proposal = Relationship(
        back_populates="variations",
        sa_relationship_kwargs={
            "lazy": "selectin",
            "foreign_keys": "[ProposalVariation.proposal_id]",
        },
    )

    # ==================== Helper Methods ====================

    @property
    def persona_display_name(self) -> str:
        """Get human-readable persona name."""
        return self.agent_persona.value.replace("_", " ").title()

    @property
    def is_high_confidence(self) -> bool:
        """Check if confidence score is high (>70)."""
        return self.confidence_score > 70

    def add_chat_message(self, role: str, content: str) -> None:
        """
        Add a message to chat history.

        Args:
            role: Message role (user/assistant)
            content: Message content

        NOTE: We must reassign to a *new* list rather than calling .append()
        on the existing one. SQLAlchemy tracks changes to JSONB columns by
        identity — in-place mutations are invisible to the ORM and won't be
        flushed to the database.
        """
        existing = list(self.chat_history) if self.chat_history else []
        existing.append(
            {
                "role": role,
                "content": content,
                "timestamp": datetime.now(timezone.utc).isoformat(),
            }
        )
        self.chat_history = existing

    def __repr__(self) -> str:
        """String representation for debugging."""
        return f"<ProposalVariation(id={self.id}, persona={self.agent_persona.value}, confidence={self.confidence_score})>"


# ==================== TaskDocument Model ====================


class TaskDocument(SQLModel, table=True):
    """
    Document uploaded specifically for a proposal task.

    Unlike HistoricalDocuments (project-wide), TaskDocuments are specific
    to a single proposal and provide context for that task.

    Attributes:
        id: Primary key
        filename: Original filename
        content_text: Extracted text content
        file_size_bytes: File size
        mime_type: Content type
        proposal_id: Parent proposal (FK)
        uploader_id: User who uploaded (FK)
        uploaded_at: Upload timestamp
    """

    __tablename__ = "task_documents"

    # ==================== Primary Key ====================

    id: Optional[int] = Field(
        default=None,
        primary_key=True,
        description="Task document ID",
    )

    # ==================== File Metadata ====================

    filename: str = Field(
        max_length=255,
        sa_column=Column(String(255), nullable=False),
        description="Original filename",
    )

    file_size_bytes: Optional[int] = Field(
        default=None,
        description="File size in bytes",
    )

    mime_type: Optional[str] = Field(
        default=None,
        max_length=100,
        description="MIME type",
    )

    # ==================== Content ====================

    content_text: str = Field(
        sa_column=Column(Text, nullable=False),
        description="Extracted text content",
    )

    # ==================== Foreign Keys ====================

    proposal_id: int = Field(
        foreign_key="proposals.id",
        index=True,
        description="Parent proposal ID",
    )

    uploader_id: int = Field(
        foreign_key="users.id",
        index=True,
        description="User who uploaded this document",
    )

    # ==================== Timestamps ====================

    uploaded_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc).replace(tzinfo=None),
        nullable=False,
        description="Upload timestamp (UTC)",
    )

    # ==================== Relationships ====================

    proposal: "Proposal" = Relationship(
        back_populates="task_documents",
        sa_relationship_kwargs={"lazy": "selectin"},
    )

    uploader: Optional["User"] = Relationship(
        sa_relationship_kwargs={"lazy": "selectin"},
    )

    # ==================== Helper Methods ====================

    @property
    def file_size_mb(self) -> float:
        """Get file size in megabytes."""
        if not self.file_size_bytes:
            return 0.0
        return self.file_size_bytes / (1024 * 1024)

    def __repr__(self) -> str:
        """String representation for debugging."""
        return f"<TaskDocument(id={self.id}, filename={self.filename!r})>"
