"""
Baseline service for single-agent proposal generation (Condition A).

Thesis experimental design:
    - Condition A (Baseline): Single generic AI agent
    - Condition B (Treatment): Multi-agent Council debate

This service generates Condition A proposals for A/B comparison in RQ1 and RQ3:
    - RQ1: Do multi-agent proposals have higher trust scores?
    - RQ3: Does multi-agent debate reach consensus faster/better?

Baseline proposals:
    - Use the same RAG context as multi-agent (fair comparison)
    - Single AI call with generic architect persona
    - Stored as ProposalVariation with persona="baseline"
    - Evaluated by participants using the same questionnaire

Implementation notes:
    - Baseline should produce output structurally similar to Council
    - Same quality attributes should be extractable for comparison
    - Generation time tracked for RQ3 efficiency metrics
"""

import structlog
from datetime import datetime, timezone

from sqlmodel.ext.asyncio.session import AsyncSession

from app.models.proposal import Proposal, ProposalVariation, AgentPersona
from app.core.config import settings
from app.core.exceptions import (
    NotFoundException,
    AIServiceException,
)
from app.services.vector_service import VectorService
from app.services.ai import ai_service

logger = structlog.get_logger()


class BaselineService:
    """
    Service for generating single-agent baseline proposals.

    Produces Condition A proposals for thesis A/B testing.
    Uses identical RAG context as multi-agent to ensure fair comparison.
    """

    def __init__(self, session: AsyncSession):
        self.session = session
        self.vector_service = VectorService(session=session)

    # ==================== Baseline Generation ====================

    async def generate_baseline_proposal(
        self,
        proposal_id: int,
    ) -> ProposalVariation:
        """
        Generate a baseline proposal using a single generic AI agent.

        Creates a ProposalVariation record with persona="baseline" for
        comparison against multi-agent proposals in thesis evaluation.

        Args:
            proposal_id: Proposal to generate baseline for

        Returns:
            ProposalVariation: Saved baseline proposal variation

        Raises:
            NotFoundException: If proposal not found
            AIServiceException: If AI generation fails
        """
        log = logger.bind(
            operation="generate_baseline",
            proposal_id=proposal_id,
        )

        # Fetch proposal
        proposal = await self.session.get(Proposal, proposal_id)
        if not proposal:
            raise NotFoundException(f"Proposal {proposal_id} not found")

        start_time = datetime.now(timezone.utc).replace(tzinfo=None)

        # Retrieve RAG context (same as multi-agent uses)
        rag_context = await self._get_rag_context(proposal)

        # Build prompt
        prompt = self._build_baseline_prompt(
            task_description=proposal.task_description,
            rag_context=rag_context,
        )

        log.info("generating_baseline_proposal", prompt_length=len(prompt))

        # Generate baseline proposal
        try:
            response_text = await ai_service.generate_text(
                system_prompt=self._get_baseline_system_prompt(),
                user_prompt=prompt,
                model=settings.ANTHROPIC_MODEL,
                max_tokens=2000,
                temperature=0.7,  # Same as multi-agent
            )
        except Exception as e:
            log.error("baseline_generation_failed", error=str(e))
            raise AIServiceException(f"Failed to generate baseline proposal: {str(e)}")

        end_time = datetime.now(timezone.utc).replace(tzinfo=None)
        generation_time = (end_time - start_time).total_seconds()

        log.info(
            "baseline_generated",
            response_length=len(response_text),
            duration_seconds=generation_time,
        )

        # Extract quality attributes for comparison
        qa_mentioned = self._extract_quality_attributes(response_text)

        # Create ProposalVariation with persona="baseline"
        variation = ProposalVariation(
            proposal_id=proposal_id,
            agent_persona=AgentPersona.BASELINE,
            structured_prd=response_text,
            reasoning=(
                f"Generated by single generic AI agent (Condition A). "
                f"QA attributes detected: {', '.join(qa_mentioned) if qa_mentioned else 'none'}."
            ),
            trade_offs=None,
            confidence_score=70,
            chat_history=[],
            generation_seconds=round(generation_time, 3),
        )

        self.session.add(variation)
        await self.session.commit()
        await self.session.refresh(variation)

        log.info(
            "baseline_variation_saved",
            variation_id=variation.id,
            qa_count=len(qa_mentioned),
        )

        return variation

    # ==================== RAG Context ====================

    async def _get_rag_context(self, proposal: Proposal) -> str:
        """
        Retrieve RAG context for the proposal.

        Uses the same retrieval logic as multi-agent debates
        to ensure fair comparison (same knowledge base).

        Args:
            proposal: Proposal being evaluated

        Returns:
            str: Formatted RAG context
        """
        try:
            chunks = await self.vector_service.hybrid_search(
                query=proposal.task_description,
                limit=5,
            )

            if chunks:
                context = "\n\n".join(
                    [
                        f"[Document {c.document_id}, Chunk {c.chunk_index}]:\n{c.content}"
                        for c in chunks
                    ]
                )
                logger.info("baseline_rag_context_retrieved", chunks=len(chunks))
                return context
            else:
                return "No relevant project documentation found."

        except Exception as e:
            logger.error("baseline_rag_retrieval_failed", error=str(e))
            return "Documentation retrieval failed. Proceeding without context."

    # ==================== Prompt Building ====================

    def _get_baseline_system_prompt(self) -> str:
        """
        System prompt for baseline single-agent generation (Condition A).

        Deliberately presents as a single, generic senior architect with no
        specialised persona framing. Output structure mirrors the multi-agent
        synthesis for fair comparison, but all perspectives come from one voice.
        """
        return """You are a senior software architect. Your task is to produce a clear, thorough architectural proposal that a development team can evaluate and implement.

Produce well-reasoned recommendations. Cover the technical design, key trade-offs, technology choices, implementation approach, and risks. Be direct and specific — name technologies, cite constraints, give concrete recommendations rather than abstract options.

Do not adopt any particular ideological stance (e.g. "always modernise" or "always preserve"). Reason from first principles based on the specific problem and constraints given."""

    def _build_baseline_prompt(
        self,
        task_description: str,
        rag_context: str,
    ) -> str:
        """
        Build the user prompt for baseline generation.

        Args:
            task_description: Original proposal task
            rag_context: Retrieved context from documents

        Returns:
            str: Formatted user prompt
        """
        return f"""
PROJECT CONTEXT (from internal documentation):
{rag_context}

ARCHITECTURAL TASK:
{task_description}

YOUR TASK:
Design a comprehensive architectural proposal that addresses this requirement.
Structure your response as follows:

1. **High-Level Architecture Overview**
   - Core architectural pattern and design principles
   - Key components and their interactions

2. **Component Breakdown**
   - Detailed description of each major component
   - Responsibilities and interfaces

3. **Quality Attributes & Trade-offs**
   - How the design addresses quality attributes (reliability, scalability, security, maintainability, performance)
   - Key trade-offs and rationale

4. **Technology Choices**
   - Recommended technologies and frameworks
   - Justification for each choice

5. **Implementation Roadmap**
   - Phased approach to implementation
   - Critical dependencies and milestones

6. **Risk Assessment & Mitigation**
   - Identified risks
   - Concrete mitigation strategies

Be thorough, practical, and balanced in your recommendations.
""".strip()

    # ==================== Quality Attribute Extraction ====================

    def _extract_quality_attributes(self, response: str) -> list[str]:
        """
        Extract mentioned quality attributes from baseline response.

        Uses the same attribute list as multi-agent for fair comparison.

        Args:
            response: Generated baseline proposal text

        Returns:
            List[str]: Quality attributes mentioned
        """
        # Comprehensive quality attribute list (ISO 25010 + practical extensions)
        quality_attributes = [
            "Reliability",
            "Maintainability",
            "Security",
            "Performance",
            "Scalability",
            "Availability",
            "Usability",
            "Testability",
            "Modularity",
            "Extensibility",
            "Portability",
            "Interoperability",
            "Monitoring",
            "Observability",
            "Cost-effectiveness",
            "Agility",
            "Resilience",
            "Compliance",
        ]

        response_lower = response.lower()
        mentioned = [
            attr for attr in quality_attributes if attr.lower() in response_lower
        ]

        return mentioned
