"""
Proposal factory fixtures.

Covers ProposalStatus, ApprovalStatus, AgentPersona, and ProposalVariation
so proposal service and API tests don't repeat boilerplate.
"""

from __future__ import annotations

import pytest
from datetime import datetime, timezone

from app.models.proposal import (
    Proposal,
    ProposalVariation,
    ProposalStatus,
    ApprovalStatus,
    AgentPersona,
)


# ── Low-level factories ────────────────────────────────────────────────────────


def build_proposal(
    id: int = 1,
    task_description: str = "Migrate monolith to microservices architecture",
    status: ProposalStatus = ProposalStatus.COMPLETED,
    approval_status: ApprovalStatus = ApprovalStatus.DRAFT,
    project_id: int = 1,
    created_by_id: int = 1,
    structured_prd: str | None = "# PRD\n\nThis proposal covers migration strategy.",
    error_message: str | None = None,
    selected_variation_id: int | None = None,
) -> Proposal:
    """
    Build an in-memory Proposal.

    Defaults to COMPLETED status (generation succeeded) + DRAFT approval.
    """
    now = datetime.now(timezone.utc).replace(tzinfo=None)
    return Proposal(
        id=id,
        task_description=task_description,
        structured_prd=structured_prd,
        status=status,
        approval_status=approval_status,
        error_message=error_message,
        selected_variation_id=selected_variation_id,
        project_id=project_id,
        created_by_id=created_by_id,
        created_at=now,
        updated_at=now,
    )


def build_proposal_variation(
    id: int = 1,
    proposal_id: int = 1,
    agent_persona: AgentPersona = AgentPersona.MEDIATOR,
    structured_prd: str | None = "# Variation PRD\n\nMediator balanced approach.",
    confidence_score: int = 75,
    reasoning: str | None = "Balanced trade-off between stability and innovation.",
    trade_offs: str | None = "Higher upfront cost; lower long-term risk.",
) -> ProposalVariation:
    """
    Build an in-memory ProposalVariation.

    Args:
        id:               PK
        proposal_id:      FK to parent Proposal
        agent_persona:    Which AI persona generated this
        structured_prd:   PRD markdown content
        confidence_score: 0-100 confidence rating
        reasoning:        Explanation of approach
        trade_offs:       Identified trade-offs
    """
    now = datetime.now(timezone.utc).replace(tzinfo=None)
    return ProposalVariation(
        id=id,
        proposal_id=proposal_id,
        agent_persona=agent_persona,
        structured_prd=structured_prd,
        confidence_score=confidence_score,
        reasoning=reasoning,
        trade_offs=trade_offs,
        created_at=now,
    )


def build_draft_proposal(id: int = 1, project_id: int = 1) -> Proposal:
    """Proposal in DRAFT/DRAFT state — just created, nothing generated yet."""
    return build_proposal(
        id=id,
        project_id=project_id,
        status=ProposalStatus.DRAFT,
        approval_status=ApprovalStatus.DRAFT,
        structured_prd=None,
    )


def build_processing_proposal(id: int = 1, project_id: int = 1) -> Proposal:
    """Proposal currently being generated by AI agents."""
    return build_proposal(
        id=id,
        project_id=project_id,
        status=ProposalStatus.PROCESSING,
        structured_prd=None,
    )


def build_approved_proposal(id: int = 1, project_id: int = 1) -> Proposal:
    """Fully completed and approved proposal."""
    return build_proposal(
        id=id,
        project_id=project_id,
        status=ProposalStatus.COMPLETED,
        approval_status=ApprovalStatus.APPROVED,
    )


def build_failed_proposal(id: int = 1, project_id: int = 1) -> Proposal:
    """Proposal whose generation failed."""
    return build_proposal(
        id=id,
        project_id=project_id,
        status=ProposalStatus.FAILED,
        structured_prd=None,
        error_message="Claude API rate limit exceeded after 3 retries",
    )


def build_all_persona_variations(proposal_id: int = 1) -> list[ProposalVariation]:
    """
    Return one variation per AgentPersona (LEGACY_KEEPER, INNOVATOR, MEDIATOR).
    """
    return [
        build_proposal_variation(
            id=1,
            proposal_id=proposal_id,
            agent_persona=AgentPersona.LEGACY_KEEPER,
            structured_prd="# Legacy Keeper PRD\n\nStability-first approach.",
            confidence_score=80,
            reasoning="Minimise disruption to existing systems.",
        ),
        build_proposal_variation(
            id=2,
            proposal_id=proposal_id,
            agent_persona=AgentPersona.INNOVATOR,
            structured_prd="# Innovator PRD\n\nGreenfield modernisation.",
            confidence_score=70,
            reasoning="Full cloud-native rewrite for velocity.",
        ),
        build_proposal_variation(
            id=3,
            proposal_id=proposal_id,
            agent_persona=AgentPersona.MEDIATOR,
            structured_prd="# Mediator PRD\n\nStrangler-fig pattern.",
            confidence_score=75,
            reasoning="Incremental migration balances risk and speed.",
        ),
    ]


# ── pytest fixtures ────────────────────────────────────────────────────────────


@pytest.fixture
def test_proposal() -> Proposal:
    """Completed DRAFT-approval proposal (ready for review)."""
    return build_proposal()


@pytest.fixture
def test_approved_proposal() -> Proposal:
    """Fully approved proposal."""
    return build_approved_proposal()


@pytest.fixture
def test_draft_proposal() -> Proposal:
    """Fresh proposal — not yet generated."""
    return build_draft_proposal()


@pytest.fixture
def test_failed_proposal() -> Proposal:
    """Proposal with a generation failure."""
    return build_failed_proposal()


@pytest.fixture
def test_proposal_variations() -> list[ProposalVariation]:
    """All three persona variations for proposal id=1."""
    return build_all_persona_variations()


@pytest.fixture
def make_proposal():
    """
    Parameterizable proposal factory.

    Usage:
        def test_custom(make_proposal):
            p = make_proposal(id=5, project_id=2, status=ProposalStatus.FAILED)
    """
    return build_proposal


@pytest.fixture
def make_proposal_variation():
    """
    Parameterizable variation factory.

    Usage:
        def test_variation(make_proposal_variation):
            v = make_proposal_variation(agent_persona=AgentPersona.INNOVATOR)
    """
    return build_proposal_variation
