import React from 'react';
import { X, Zap, Shield, Cpu } from 'lucide-react';
import type { ProposalVariation } from '../../types';

interface DetailModalHeaderProps {
    selectedVariation: ProposalVariation;
    onClose: () => void;
}

export const DetailModalHeader: React.FC<DetailModalHeaderProps> = ({ selectedVariation, onClose }) => {

    const getPersonaTheme = (persona: string) => {
        switch (persona) {
            case 'Innovator':
                return {
                    bg: 'bg-purple-100 text-purple-600',
                    icon: <Zap size={24} />
                };
            case 'Legacy Keeper':
                return {
                    bg: 'bg-slate-100 text-slate-600',
                    icon: <Shield size={24} />
                };
            default:
                return {
                    bg: 'bg-blue-100 text-blue-600',
                    icon: <Cpu size={24} />
                };
        }
    };

    const theme = getPersonaTheme(selectedVariation.agent_persona);

    return (
        <div className="bg-white border-b border-slate-100 p-6 flex justify-between items-center flex-shrink-0 z-10">
            <div className="flex items-center gap-4">
                <div className={`p-3 rounded-xl ${theme.bg}`}>
                    {theme.icon}
                </div>
                <div>
                    <h2 className="text-2xl font-bold text-slate-900">
                        {selectedVariation.agent_persona} Proposal
                    </h2>
                    <p className="text-sm text-slate-500 flex items-center gap-2">
                        <span className="font-medium text-slate-900">
                            {selectedVariation.confidence_score}% Viability Score
                        </span>
                        • Generated by The Council
                    </p>
                </div>
            </div>
            <button
                onClick={onClose}
                className="p-2 hover:bg-slate-100 rounded-full text-slate-400 hover:text-slate-800 transition"
            >
                <X size={28} />
            </button>
        </div>
    );
};